INSERT INTO complaints (Complaint_ID, complaint, comment, resolved) VALUES
(5524, 'The wine I purchased was corked and tasted sour. I need a refund or replacement.', '', false),
(2174, 'The fruits in the pre-packaged bag were rotten when I opened them. This is unacceptable.', '', false),
(4141, 'The meat I bought had a foul odor despite being within its expiration date.', '', false),
(6182, 'The fish was not fresh and had an unpleasant smell as soon as I unpacked it.', '', false),
(5324, 'The sweets were stale and tasted like they had been sitting on the shelf for weeks.', '', false),
(7446, 'The gold chain I purchased broke within a week of use. Poor quality!', '', false),
(965, 'The wine bottle label was misleading—it was not the vintage I ordered.', '', false),
(6177, 'The fruit basket I received had bruised and inedible items in it.', '', false),
(4855, 'The steak I bought shrank significantly while cooking and was not tender.', '', false),
(5899, 'The fish fillets were not deboned properly and had many sharp bones.', '', false),
(1994, 'The chocolates were melted and misshapen when I received them.', '', false),
(387, 'The gold ring sizing was completely off, even though I provided the correct size.', '', false),
(2125, 'The wine was labeled as dry, but it was overly sweet and not to my liking.', '', false),
(8180, 'The fruit salad had pieces that were moldy and unappetizing.', '', false),
(2569, 'The meat pack contained freezer-burned cuts, which is not what I paid for.', '', false),
(2114, 'The fish steaks were improperly cut and had scales left on them.', '', false),
(9736, 'The candy bag was torn open when I picked it up from the shelf.', '', false),
(4939, 'The gold bracelet clasp broke the first time I tried to wear it.', '', false),
(6565, 'The wine delivery was delayed, and the bottle arrived warm and damaged.', '', false),
(2278, 'The mixed fruit box had a sour smell and several fruits were overripe.', '', false),
(9360, 'The meatballs contained gristle, making them very unpleasant to eat.', '', false);
